import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ArrowUp, Menu, X, BookOpen, Landmark, Calculator, FlaskConical, Users, CalendarDays, ChartNoAxesCombined, MapPin, Phone, Mail, Play, ClipboardCheck, Send} from 'lucide-react';
import './style.css';
import './responsive.css';
import Journey from './Journey';
import {installScrollLimit} from './smooth-scroll';

if(import.meta.hot)import.meta.hot.dispose(()=>window.__pacedScroll?.());
window.__pacedScroll?.();
window.__pacedScroll=installScrollLimit();

const links=[['Home','home'],['About','about'],['Courses','courses'],['Subjects','subjects'],['Why Us','whyus'],['Contact','contact']];
const streams=[
 {name:'Commerce', icon:ChartNoAxesCombined, tone:'blue', subjects:['Business Studies','Accountancy','Computer Application','Economics','Political Science','English']},
 {name:'Humanities', icon:Landmark, tone:'violet', subjects:['History','Economics','Political Science','Sociology','Computer Application']},
 {name:'Accounting', icon:Calculator, tone:'mint', subjects:['Tally Prime','DIFA']}
];
const features=[['Full Subjects Tuition Including English',BookOpen],['Experienced Faculties',Users],['Practical Lab',FlaskConical],['Continuous Examination',ClipboardCheck],['Parents Meeting',Users],['Monthly Unit Test',CalendarDays],['Monitoring & Evaluation',ChartNoAxesCombined]];
const Marker=({n,label})=><div className="marker"><b>{n}</b><span>{label}</span></div>;
function Logo(){return <a className="logo" href="#home" aria-label="AB’S Learning Hub — home"><img src="/abs-logo.webp" alt="AB’S Learning Hub" width="90" height="70"/></a>}
function Button({children, light=false, href='#courses'}){return <a href={href} className={'button '+(light?'light':'')}>{children}<ArrowRight size={17}/></a>}
function Header(){
 const [open,setOpen]=useState(false),[active,setActive]=useState('home');
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)})},{rootMargin:'-15% 0px -55% 0px'});links.forEach(([,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 return <header><div className="header-inner"><Logo/><nav id="navigation" aria-label="Main navigation" className={open?'open':''}>{links.map(([name,id])=><a key={id} aria-current={active===id?'location':undefined} onClick={()=>setOpen(false)} href={'#'+id}>{name}</a>)}</nav><Button href="#contact">Join Us</Button><button className="menu" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
}
function StreamCard({s,compact=false}){const Icon=s.icon;return <article className={'stream '+s.tone+(compact?' compact':'')}><div className="stream-title"><Icon aria-hidden="true"/><h3>{s.name}{compact?' Subjects':''}</h3></div><ul>{s.subjects.map(x=><li key={x}>{x}</li>)}</ul></article>}
function App(){return <><a className="skip-link" href="#courses">Skip to courses</a><Header/><main><Journey/>
 <section id="home" className="hero section"><div className="hero-copy"><p className="eyebrow">A brighter tomorrow starts here</p><h1>Bright Your Future<br/>With <em>AB’S<br/>Learning Hub</em></h1><p>Focused learning. Experienced faculties. Practical exposure.<br className="desktop-break"/> Regular examinations. Continuous support. A stronger you<br className="desktop-break"/> for a brighter tomorrow.</p><div className="actions"><Button>Explore Courses</Button><Button light href="#about"><Play fill="currentColor" size={17}/>Discover AB’S</Button></div><div className="learn">Learn <i/> Grow <i/> Lead</div></div><div className="hero-art" role="img" aria-label="Illustrated learning campus"><div className="campus-brand"><img src="/abs-logo.webp" alt=""/></div></div><div className="note hero-note">Every great<br/>future starts<br/>with a step</div><div className="start-marker"><Marker n="01" label={<>Start<br/>Your Journey</>}/></div></section>
 <section id="courses" className="section courses"><div className="course-art" aria-hidden="true"><img className="signpost" src="/signpost.png" alt="" loading="lazy"/></div><div className="course-content"><div className="copy"><Marker n="02" label="Our Courses"/><h2>Choose Your Path</h2><p>Three focused streams. A stronger future.<br/>Discover the right path for your goals.</p></div><div className="stream-grid">{streams.map(s=><StreamCard key={s.name} s={s}/>)}</div></div></section>
 <section id="subjects" className="section subjects"><div className="copy"><Marker n="03" label="Our Subjects"/><h2>Build Strong Foundations</h2><p>A well-structured curriculum to help you learn,<br/>practice and achieve higher.</p><Button href="#subject-list">View All Subjects</Button></div><div className="note subjects-note">Knowledge<br/>Today,<br/>Brighter<br/>Tomorrow</div><div className="subject-art" aria-hidden="true"><img className="books" src="/books.png" alt="" loading="lazy"/></div><div id="subject-list" className="subject-grid">{streams.map(s=><StreamCard key={s.name} s={s} compact/>)}</div></section>
 <section id="whyus" className="section why"><div className="copy"><Marker n="04" label="Why Choose AB’S"/><h2>More Than Just Tuition</h2><p>A supportive environment, better learning outcomes,<br/>and a brighter future.</p></div><div className="feature-grid">{features.map(([name,Icon])=><article className="feature" key={name}><Icon aria-hidden="true"/><span>{name}</span></article>)}<div className="note">Small Steps<br/>Big Futures</div></div></section>
 <section id="about" className="section about"><div className="copy"><Marker n="05" label="About AB’S Learning Hub"/><h2>Focused Learning<br/>For Real Growth</h2><p>At AB’S Learning Hub, we focus on building strong foundations through quality teaching, practical exposure, regular examinations and continuous support. We work closely with students and parents to ensure steady progress, confidence and long-term success.</p><Button href="#contact">Know More About Us</Button></div><div className="room" role="img" aria-label="Illustrated learning space"><img className="room-logo" src="/abs-logo.webp" alt=""/><div className="note">Better<br/>Students<br/>Brighter<br/>Tomorrows</div></div></section>
 <section id="future" className="section future"><div className="copy"><Marker n="06" label="Your Future Awaits"/><h2>Learn Today.<br/>Grow Tomorrow.</h2><p>With the right learning, support and mindset,<br/>you can achieve everything you aspire to.</p><Button href="#contact">Start Your Journey</Button></div><div className="mountains" role="img" aria-label="Sunlit mountain valley and an open rocky overlook"/><div className="note future-note">Bigger<br/>Dreams<br/>Brighter<br/>Tomorrows</div></section>
 <section id="contact" className="section contact"><div className="copy"><Marker n="07" label="Get In Touch"/><h2>Let’s Make Your<br/>Future Brighter</h2><p>Have questions? Want to know more about our courses?<br/>We’d love to hear from you.</p><Button href="mailto:abslearninghub7025@gmail.com">Enquire Now</Button></div><div className="contact-note note"><Send/>Take the<br/>Next Step</div><div className="contact-cards"><a href="https://maps.google.com/?q=Soorya+Arcade+Mannur+Valavu"><MapPin/><div><b>Address</b><span>Soorya Arcade,<br/>Near Kallampara Bridge,<br/>Mannur Valavu</span></div></a><a href="tel:+917025293116"><Phone/><div><b>Phone</b><span>+91 7025 293 116</span></div></a><a href="mailto:abslearninghub7025@gmail.com"><Mail/><div><b>Email</b><span>abslearninghub7025@gmail.com</span></div></a></div></section>
 </main><footer><div className="footer-top"><div className="footer-brand"><Logo/><div><strong>AB’S</strong><b>LEARNING HUB</b><small>Learn · Grow · Lead</small></div></div><nav aria-label="Footer navigation">{links.map(([name,id])=><a key={id} href={'#'+id}>{name}</a>)}</nav><a className="back-top" href="#home" aria-label="Back to top"><ArrowUp/></a></div><div className="footer-bottom"><small>© {new Date().getFullYear()} AB’S Learning Hub. All rights reserved.</small><span>Education Builds Brighter Futures.</span></div></footer></>}
const root=import.meta.hot?.data.root??createRoot(document.getElementById('root'));
if(import.meta.hot)import.meta.hot.data.root=root;
root.render(<App/>);
